name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          # Variáveis
          HOST=${{ secrets.EC2_HOST }}
          USER=${{ secrets.EC2_USER }}

          # Conectar via SSH e preparar o ambiente
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            # Criar o diretório se não existir
            mkdir -p /home/$USER/app
          EOF

          # Upload arquivos para EC2
          scp -o StrictHostKeyChecking=no -r ./* $USER@$HOST:/home/$USER/app/

          # Conectar via SSH e iniciar Docker containers
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd /home/$USER/app

            # Construir e iniciar Docker containers
            docker-compose up --build -d
          EOF
