name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          scp -r ./zookeeper ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app/
          scp -r ./eureka ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app/
          scp -r ./micro-producer ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app/
          scp -r ./micro-consumer ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app/
          scp -r ./api-gateway ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app/

      - name: Deploy on EC2
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ec2-user/app/zookeeper
          docker build -t zookeeper .
          docker run -d --name zookeeper zookeeper

          cd /home/ec2-user/app/eureka
          docker build -t eureka .
          docker run -d --name eureka --link zookeeper:zookeeper eureka

          cd /home/ec2-user/app/micro-producer
          docker build -t micro-producer .
          docker run -d --name micro-producer --link eureka:eureka micro-producer

          cd /home/ec2-user/app/micro-consumer
          docker build -t micro-consumer .
          docker run -d --name micro-consumer --link micro-producer:micro-producer micro-consumer

          cd /home/ec2-user/app/api-gateway
          docker build -t api-gateway .
          docker run -d --name api-gateway --link micro-consumer:micro-consumer api-gateway

          docker ps
          EOF
